linters:
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
  enable:
    # Default linters
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - goimports
    - gofmt
